name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: markdown-lint
        uses: articulate/actions-markdownlint@v1.1.0
        with:
          config: .markdownlint.yaml
